name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: Product website
      url: https://github.com
        # ...deployment-specific steps
